CREATE TABLE dados (
    AlunoID INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Sobrenome VARCHAR(50) NOT NULL,
    Endereco VARCHAR(150) NOT NULL,
    Cidade VARCHAR(50) NOT NULL,
    Host VARCHAR(50) NOT NULL,
    DataCadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
